# Generated by Django 4.1 on 2023-08-12 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('Sisoft', 'Sisoft'), ('TSK Ağı', 'TSK Ağı'), ('MSB Ağı', 'MSB Ağı'), ('Terminal', 'Terminal'), ('Bilgisayar', 'Bilgisayar'), ('Kamera', 'Kamera'), ('Telefon', 'Telefon'), ('Yazıcı', 'Yazıcı'), ('Diğer - MEBS', 'Diğer - MEBS'), ('Diğer - MEBS DIŞI', 'Diğer - MEBS DIŞI')], max_length=50)),
                ('post_type', models.CharField(choices=[('İşlem', 'İşlem'), ('Arıza Çözüm', 'Arıza Çözüm')], max_length=20)),
                ('content', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
