# Generated by Django 4.2.4 on 2023-08-22 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gonderiyaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('İşlem', 'İşlem'), ('Arıza Çözüm', 'Arıza Çözüm'), ('Teori', 'Teori')], default='İşlem', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipient_type',
            field=models.CharField(choices=[('Sisoft', 'Sisoft'), ('TSK Ağı', 'TSK Ağı'), ('MSB Ağı', 'MSB Ağı'), ('Terminal', 'Terminal'), ('Bilgisayar', 'Bilgisayar'), ('Kamera', 'Kamera'), ('Telefon', 'Telefon'), ('Yazıcı', 'Yazıcı'), ('Diğer - MEBS', 'Diğer - MEBS'), ('Diğer - MEBS DIŞI', 'Diğer - MEBS DIŞI')], default='Sisoft', max_length=50),
        ),
    ]
